Create DATABASE CARHIREDATABASE;
use CARHIREDATABASE;

CREATE TABLE IF NOT EXISTS Orders (
	OrderID int NOT NULL AUTO_INCREMENT,
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	CustID int NOT NULL,
	CarReg varchar(12),
	PRIMARY KEY (OrderID)
);

INSERT INTO Orders (OrderID, StartDate, EndDate, CustID, CarReg)
VALUES (1, CURDATE(), CURDATE(), 11, "02-G-123"), 
       (2, CURDATE(), CURDATE(), 21, "02-G-125"), 
	   (3, CURDATE(), CURDATE(), 31, "02-G-124");
	   
SELECT * FROM Orders;